# Dockerfile.dev
FROM node:18-alpine

WORKDIR /app

# رجیستری npm و تلاش مجدد در صورت خطا
RUN npm config set registry https://registry.npmmirror.com
RUN npm config set fetch-retries 5 && npm config set fetch-retry-mintimeout 20000 && npm config set fetch-retry-maxtimeout 120000

COPY package.json package-lock.json ./
RUN npm install

COPY . .

EXPOSE 3000

CMD ["npm", "run"]
# CMD ["npm", "run", "dev"]
