version: '3.8'

services:
  backend:
    container_name: astro-backend
    build: ./backend
    ports:
      - "3330:3330"
    volumes:
      - ./backend:/app
    networks:
      - astro-network

  frontend:
    container_name: astro-frontend
    build:
      context: ./frontend
      # dockerfile: Dockerfile.dev  # یا Dockerfile برای prod
      dockerfile: Dockerfile  # یا Dockerfile برای prod
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env           # برای dev (در prod تغییر بده)
    volumes:
      - ./frontend:/app
      - /app/.next
      - frontend_node_modules:/app/node_modules
      - ~/.npm:/root/.npm
    networks:
      - astro-network

networks:
  astro-network:
    driver: bridge

volumes:
  frontend_node_modules:
